#!/usr/bin/env python3
"""
enrich_leads.py
Enhanced enrichment logic — skips any lead with a live website.

Purpose:
• Enrich Directory/No‑Site leads generated by Discover Mode.
• Verify actual website existence for each discovered lead.
• Fetch up to one confirmed contact email if no valid site.

------------------------------------------------------
"""

import os, re, time, json, hashlib, requests, pandas as pd, traceback
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import urlparse
from dotenv import load_dotenv
from datetime import datetime, timedelta

SRC_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

from utils.config import get_config_bool, get_config_int
from utils.logger import emit_structured_event

# ======================================================
# ENV SETUP
# ======================================================
load_dotenv()
SERPER = os.getenv("SERPER_API_KEY")
HUNTER = os.getenv("HUNTER_API_KEY")
DEBUG = os.getenv("DEBUG", "false").lower() == "true"
LEAD_SCORE_THRESHOLD = get_config_int("enrichment.lead_score_threshold", default=2, env_var="LEAD_SCORE_THRESHOLD")
PRE_ENRICH_SCORE_FILTER = get_config_bool("enrichment.pre_enrich_score_filter", default=True, env_var="PRE_ENRICH_SCORE_FILTER")
STARTUP_PRIORITY = os.getenv("STARTUP_PRIORITY", "false").strip().lower() in {"1", "true", "yes", "on"}
STARTUP_SCORE_BOOST = int(os.getenv("STARTUP_SCORE_BOOST", "2"))
STARTUP_MAX_AGE_YEARS = int(os.getenv("STARTUP_MAX_AGE_YEARS", "5"))
STARTUP_EXCLUDE_TECH = os.getenv("STARTUP_EXCLUDE_TECH", "true").strip().lower() in {"1", "true", "yes", "on"}
STARTUP_HINT_KEYWORDS = tuple(
    token.strip().lower()
    for token in os.getenv(
        "STARTUP_HINT_KEYWORDS",
        "founded,established,since,newly opened,recently opened,just launched,new business,new company",
    ).split(",")
    if token.strip()
)
STARTUP_TECH_EXCLUDE_KEYWORDS = tuple(
    token.strip().lower()
    for token in os.getenv(
        "STARTUP_TECH_EXCLUDE_KEYWORDS",
        "saas,software,app,platform,ai,ml,machine learning,cloud,devops,fintech,edtech,martech",
    ).split(",")
    if token.strip()
)

try:
    HUNTER_MAX_DOMAINS_PER_LEAD = max(0, int(os.getenv("HUNTER_MAX_DOMAINS_PER_LEAD", "1")))
except Exception:
    HUNTER_MAX_DOMAINS_PER_LEAD = 1

SCRAPE_MAX_DOMAINS = max(1, int(os.getenv("SCRAPE_MAX_DOMAINS", "2")))
ENRICH_WORKERS = max(1, int(os.getenv("ENRICH_WORKERS", "4")))

BASE_DIR = "/Users/alexcahn/Scripts/Daily_Leads"
DATA_ROOT_DIR = os.path.join(BASE_DIR, "data")
DATA_DIR = os.path.join(DATA_ROOT_DIR, "current")
CACHE_DIR = os.path.join(DATA_DIR, "cache")
DATESTAMP = datetime.now().strftime("%Y-%m-%d")
CACHE_TTL_DAYS = int(os.getenv("CACHE_TTL_DAYS", "7"))
CACHE_MAX_MB = int(os.getenv("CACHE_MAX_MB", "256"))
RUN_METRICS_FILE = os.getenv("PIPELINE_RUN_METRICS_FILE", "")
STRUCTURED_LOGGING_ENABLED = get_config_bool(
    "logging.structured.enabled", default=True, env_var="STRUCTURED_LOGGING_ENABLED"
)

HTTP_CONNECT_TIMEOUT_SEC = 4
HTTP_READ_TIMEOUT_SEC = 8
HTTP_TIMEOUT = (HTTP_CONNECT_TIMEOUT_SEC, HTTP_READ_TIMEOUT_SEC)
HTTP_SESSION = requests.Session()

RUN_METRICS_TEMPLATE = {
    "google_places": 0,
    "serper": 0,
    "hunter": 0,
    "google_places_calls": 0,
    "google_places_success": 0,
    "google_places_error": 0,
    "google_places_cache_hit": 0,
    "google_places_latency_ms_sum": 0,
    "google_places_latency_ms_count": 0,
    "serper_calls": 0,
    "serper_success": 0,
    "serper_error": 0,
    "serper_cache_hit": 0,
    "serper_latency_ms_sum": 0,
    "serper_latency_ms_count": 0,
    "hunter_calls": 0,
    "hunter_success": 0,
    "hunter_error": 0,
    "hunter_cache_hit": 0,
    "hunter_latency_ms_sum": 0,
    "hunter_latency_ms_count": 0,
    "scrape_calls": 0,
    "scrape_success": 0,
    "scrape_error": 0,
    "scrape_cache_hit": 0,
    "scrape_latency_ms_sum": 0,
    "scrape_latency_ms_count": 0,
}

os.makedirs(CACHE_DIR, exist_ok=True)

_METRICS_LOCK = threading.Lock()

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; ZBA‑LeadBot/1.1)"}
FREE_EMAIL_DOMAINS = {
    "gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "icloud.com", "aol.com"
}

DIRECTORY_DOMAIN_HINTS = {
    "yelp.com",
    "indeed.com",
    "nextdoor.com",
    "houzz.com",
    "zocdoc.com",
    "pinterest.com",
    "medium.com",
    "facebook.com",
    "linkedin.com",
    "thumbtack.com",
    "angi.com",
    "angieslist.com",
    "yellowpages.com",
    "mapquest.com",
    "tripadvisor.com",
}

NON_BUSINESS_EMAIL_DOMAIN_HINTS = {
    "yelp.com",
    "indeed.com",
    "nextdoor.com",
    "linkedin.com",
    "instagram.com",
    "mail.instagram.com",
    "facebook.com",
    "facebookmail.com",
    "twitter.com",
    "x.com",
    "tiktok.com",
    "tiktokv.com",
    "youtube.com",
    "support.google.com",
    "pinterest.com",
    "snapchat.com",
    "reddit.com",
    "whatsapp.com",
    "discord.com",
    "telegram.org",
    "houzz.com",
    "thumbtack.com",
    "angi.com",
    "angieslist.com",
    "yellowpages.com",
    "mapquest.com",
    "zoominfo.com",
    "manta.com",
    "care.com",
    "carfax.com",
}


def sanitize_for_filename(value: str) -> str:
    return re.sub(r'[^A-Za-z0-9_]+', '_', str(value).strip()).strip('_')


def _cache_path(prefix: str, key: str) -> str:
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
    return os.path.join(CACHE_DIR, f"{prefix}_{digest}.json")


def cache_get(prefix: str, key: str):
    path = _cache_path(prefix, key)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            payload = json.load(f)
        created = datetime.fromisoformat(payload.get("created_at", "1970-01-01T00:00:00"))
        if datetime.now() - created > timedelta(days=CACHE_TTL_DAYS):
            return None
        provider = metric_provider_for_cache_prefix(prefix)
        if provider:
            increment_metric(f"{provider}_cache_hit")
        return payload.get("value")
    except Exception:
        return None


def cache_set(prefix: str, key: str, value):
    path = _cache_path(prefix, key)
    payload = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "value": value,
    }
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f)
    except Exception:
        pass


def load_run_metrics():
    data = dict(RUN_METRICS_TEMPLATE)
    if not RUN_METRICS_FILE or not os.path.isfile(RUN_METRICS_FILE):
        return data
    try:
        with open(RUN_METRICS_FILE, "r", encoding="utf-8") as f:
            loaded = json.load(f)
        for key in data:
            data[key] = int(loaded.get(key, 0) or 0)
    except Exception:
        pass
    return data


def save_run_metrics(data):
    if not RUN_METRICS_FILE:
        return
    try:
        with open(RUN_METRICS_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f)
    except Exception:
        pass


def increment_metric(metric_key: str, amount: int = 1):
    if not RUN_METRICS_FILE:
        return
    with _METRICS_LOCK:
        try:
            data = load_run_metrics()
            if metric_key in data:
                data[metric_key] += int(amount)
                save_run_metrics(data)
        except Exception:
            pass


def increment_api_counter(provider: str):
    """Backward-compatible shim for legacy tests/callers."""
    increment_metric(provider)


def metric_provider_for_cache_prefix(prefix: str) -> str:
    if (prefix or "").startswith("google_place") or prefix == "google_places":
        return "google_places"
    if prefix == "serper":
        return "serper"
    if prefix == "hunter":
        return "hunter"
    if prefix == "scrape":
        return "scrape"
    return ""


def record_api_outcome(provider: str, success: bool, latency_ms: int):
    if provider not in {"google_places", "serper", "hunter", "scrape"}:
        return
    increment_metric(provider)
    increment_metric(f"{provider}_calls")
    increment_metric(f"{provider}_success" if success else f"{provider}_error")
    increment_metric(f"{provider}_latency_ms_sum", max(0, int(latency_ms)))
    increment_metric(f"{provider}_latency_ms_count")


def run_tracked_api_call(provider: str, request_func):
    started = time.perf_counter()
    try:
        result = request_func()
        latency_ms = int((time.perf_counter() - started) * 1000)
        record_api_outcome(provider, success=True, latency_ms=latency_ms)
        return result
    except Exception:
        latency_ms = int((time.perf_counter() - started) * 1000)
        record_api_outcome(provider, success=False, latency_ms=latency_ms)
        raise


def prune_expired_cache():
    cutoff = datetime.now() - timedelta(days=CACHE_TTL_DAYS)
    removed = 0
    if not os.path.isdir(CACHE_DIR):
        return removed
    for name in os.listdir(CACHE_DIR):
        if not name.endswith(".json"):
            continue
        path = os.path.join(CACHE_DIR, name)
        try:
            with open(path, "r", encoding="utf-8") as f:
                payload = json.load(f)
            created = datetime.fromisoformat(payload.get("created_at", "1970-01-01T00:00:00"))
            if created < cutoff:
                os.remove(path)
                removed += 1
        except Exception:
            pass
    if removed:
        print(f"[CACHE] Pruned {removed} expired cache file(s).")
    return removed


def prune_cache_size_limit():
    if CACHE_MAX_MB <= 0 or not os.path.isdir(CACHE_DIR):
        return 0

    limit_bytes = CACHE_MAX_MB * 1024 * 1024
    files = []
    total_size = 0

    for name in os.listdir(CACHE_DIR):
        if not name.endswith(".json"):
            continue
        path = os.path.join(CACHE_DIR, name)
        try:
            stat = os.stat(path)
            files.append((path, stat.st_mtime, stat.st_size))
            total_size += stat.st_size
        except Exception:
            continue

    if total_size <= limit_bytes:
        return 0

    files.sort(key=lambda item: item[1])
    removed = 0
    for path, _, file_size in files:
        if total_size <= limit_bytes:
            break
        try:
            os.remove(path)
            removed += 1
            total_size -= file_size
        except Exception:
            continue

    if removed:
        print(f"[CACHE] Pruned {removed} cache file(s) to enforce CACHE_MAX_MB={CACHE_MAX_MB}.")
    return removed


prune_expired_cache()
prune_cache_size_limit()

# ======================================================
# RETRY WRAPPER
# ======================================================
def retry_request(func, *args, **kwargs):
    for attempt in range(2):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            if "429" in str(e):
                wait = 10 if attempt == 0 else 30
                print(f"[RATE] 429 Too Many Requests → waiting {wait}s…")
                time.sleep(wait)
            else:
                wait = 3 * (attempt + 1)
                print(f"[RETRY] {e} (wait {wait}s)")
                time.sleep(wait)
    print("[❌] All retries failed.")
    return None


def post_serper_with_retry(headers: dict, payload: dict, timeout: int = 25):
    """Call Serper with exponential backoff (1s, 3s, 9s) and explicit HTTP logging."""
    last_exc = None
    for attempt in range(3):
        try:
            resp = HTTP_SESSION.post(
                "https://google.serper.dev/search",
                headers=headers,
                json=payload,
                timeout=timeout,
            )
            if resp.status_code != 200:
                print(
                    f"[ERROR] Serper non-200 response: status={resp.status_code} "
                    f"attempt={attempt + 1}/3"
                )
            resp.raise_for_status()
            return resp
        except Exception as exc:
            last_exc = exc
            wait_seconds = 3 ** attempt
            print(f"[RETRY] Serper request failed attempt {attempt + 1}/3: {exc}")
            if attempt < 2:
                time.sleep(wait_seconds)
    if last_exc is not None:
        raise last_exc
    raise RuntimeError("Serper request failed without exception details")

# ======================================================
# BASIC SEARCH (SERPER)
# ======================================================
def search_serper(query):
    if not SERPER:
        return []
    cached = cache_get("serper", query)
    if cached is not None:
        return cached
    def _call():
        payload = {"q": query, "num": 5}
        headers = {"X-API-KEY": SERPER, "Content-Type": "application/json"}

        def _request():
            r = post_serper_with_retry(headers=headers, payload=payload, timeout=HTTP_TIMEOUT)
            r.raise_for_status()
            data = r.json().get("organic", [])
            return [x.get("link") for x in data if x.get("link")]

        return run_tracked_api_call("serper", _request)
    result = retry_request(_call) or []
    cache_set("serper", query, result)
    return result

# ======================================================
# WEBSITE CHECK — small HEAD request
# ======================================================
def has_live_website(domain):
    """Quickly check if the domain responds with status 200/OK + visible homepage text."""
    if not domain:
        return False

    clean_domain = (domain or "").strip().lower().replace("www.", "")
    if not clean_domain:
        return False

    for candidate in (f"https://{clean_domain}", f"http://{clean_domain}"):
        try:
            resp = HTTP_SESSION.get(candidate, headers=HEADERS, timeout=HTTP_TIMEOUT, allow_redirects=True)
            if 200 <= resp.status_code < 400:
                content_type = (resp.headers.get("Content-Type", "") or "").lower()
                body = (resp.text or "")[:3000]
                if "html" in content_type or re.search(r"<html|<!doctype", body, re.I):
                    return True
        except Exception:
            continue
    return False


def is_confirmed_business_website(url_or_domain: str, business_name: str = "") -> bool:
    value = (url_or_domain or "").strip().lower()
    if not value:
        return False

    parsed = urlparse(value if "://" in value else f"http://{value}")
    domain = (parsed.netloc or parsed.path or "").lower().replace("www.", "").strip()
    if not domain or "." not in domain:
        return False

    if any(domain == d or domain.endswith(f".{d}") for d in DIRECTORY_DOMAIN_HINTS):
        return False

    if domain.endswith(".gov") or domain.endswith(".edu"):
        return False

    # Hosted builders like Wix still indicate an existing website.
    if domain == "wixsite.com" or domain.endswith(".wixsite.com"):
        return True

    return has_live_website(domain)


def is_non_business_domain(domain: str) -> bool:
    clean_domain = (domain or "").strip().lower().replace("www.", "")
    if not clean_domain:
        return True
    return any(
        clean_domain == hint or clean_domain.endswith(f".{hint}")
        for hint in DIRECTORY_DOMAIN_HINTS
    )


def domains_look_equivalent(primary_domain: str, candidate_domain: str) -> bool:
    primary = (primary_domain or "").strip().lower().replace("www.", "")
    candidate = (candidate_domain or "").strip().lower().replace("www.", "")
    if not primary or not candidate:
        return False
    return (
        primary == candidate
        or primary.endswith(f".{candidate}")
        or candidate.endswith(f".{primary}")
    )


def is_placeholder_domain(domain: str) -> bool:
    clean = (domain or "").strip().lower().replace("www.", "")
    if not clean:
        return True
    if clean in {"example.com", "example.org", "example.net", "test.com", "localhost"}:
        return True
    return clean.startswith("example")


def business_name_matches_domain(business_name: str, domain: str) -> bool:
    business = (business_name or "").strip().lower()
    clean_domain = (domain or "").strip().lower().replace("www.", "")
    if not business or not clean_domain:
        return False

    root = clean_domain.split(".", 1)[0]
    root_alnum = re.sub(r"[^a-z0-9]", "", root)
    if not root_alnum:
        return False

    business_alnum = re.sub(r"[^a-z0-9]", "", business)
    business_alnum = re.sub(r"(llc|inc|corp|corporation|co|company)$", "", business_alnum)
    if len(business_alnum) >= 6 and (business_alnum in root_alnum or root_alnum in business_alnum):
        return True

    stopwords = {
        "the", "and", "llc", "inc", "co", "corp", "corporation", "company",
        "services", "service",
    }
    tokens = [
        tok for tok in re.findall(r"[a-z0-9]+", business)
        if len(tok) >= 3 and tok not in stopwords
    ]
    token_hits = sum(1 for tok in tokens if tok in root_alnum)
    return token_hits >= 2


def is_viable_email_address(email_addr: str) -> bool:
    value = (email_addr or "").strip().lower()
    if not value or "@" not in value:
        return False
    domain = value.split("@", 1)[1]
    if not domain or "." not in domain:
        return False
    if any(domain == hint or domain.endswith(f".{hint}") for hint in NON_BUSINESS_EMAIL_DOMAIN_HINTS):
        return False
    return True


def filter_viable_emails(emails):
    viable = []
    seen = set()
    for email_addr in emails or []:
        normalized = (email_addr or "").strip().lower()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        if is_viable_email_address(normalized):
            viable.append(normalized)
    return viable

# ======================================================
# HUNTER LOOKUP
# ======================================================
def hunter_email_lookup(domain):
    if not (HUNTER and domain):
        return []
    cached = cache_get("hunter", domain)
    if cached is not None:
        return cached
    def _call():

        def _request():
            r = HTTP_SESSION.get("https://api.hunter.io/v2/domain-search",
                                 params={"domain": domain, "api_key": HUNTER},
                                 timeout=HTTP_TIMEOUT)
            r.raise_for_status()
            emails = r.json().get("data", {}).get("emails", [])
            return [e.get("value") for e in emails if e.get("value")]

        return run_tracked_api_call("hunter", _request)
    result = retry_request(_call) or []
    cache_set("hunter", domain, result)
    return result


_CONTACT_PATHS = ("/contact", "/contact-us", "/about", "/about-us")
_EMAIL_RE = re.compile(r'[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}')


def scrape_emails_from_website(domain: str) -> list:
    """Fetch a business website and extract emails from the page text and mailto links."""
    if not domain:
        return []

    cached = cache_get("scrape", domain)
    if cached is not None:
        return cached

    increment_metric("scrape_calls")
    clean_domain = domain.lower().replace("www.", "")
    emails_found: set = set()
    started = time.perf_counter()
    had_response = False

    for scheme in ("https", "http"):
        base = f"{scheme}://{domain}"
        pages = [base] + [f"{base}{p}" for p in _CONTACT_PATHS]

        for url in pages:
            try:
                resp = HTTP_SESSION.get(
                    url, headers=HEADERS, timeout=HTTP_TIMEOUT, allow_redirects=True
                )
                if 200 <= resp.status_code < 300:
                    had_response = True
                    mailto = re.findall(
                        r'mailto:([a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,})',
                        resp.text, re.I,
                    )
                    plain = _EMAIL_RE.findall(resp.text)
                    emails_found.update(e.lower() for e in mailto + plain)
            except Exception:
                continue

        if had_response:
            break

    latency_ms = int((time.perf_counter() - started) * 1000)
    increment_metric("scrape_success" if had_response else "scrape_error")
    increment_metric("scrape_latency_ms_sum", latency_ms)
    increment_metric("scrape_latency_ms_count")

    # Prefer emails whose domain matches the site we scraped
    same_domain = [
        e for e in emails_found
        if e.split("@", 1)[-1].lower().replace("www.", "") == clean_domain
    ]
    other = [e for e in emails_found if e not in same_domain]
    result = filter_viable_emails(same_domain + other)

    cache_set("scrape", domain, result)
    return result


def pre_enrich_base_score(row):
    score = 0
    business_val = row.get("name", "")
    notes_val = row.get("notes", "")
    website_val = row.get("website", "")
    link_val = row.get("link", "")

    business = "" if pd.isna(business_val) else str(business_val).strip()
    notes = "" if pd.isna(notes_val) else str(notes_val).lower()
    website = "" if pd.isna(website_val) else str(website_val).strip()
    link = "" if pd.isna(link_val) else str(link_val).strip().lower()

    if len(business.split()) >= 2:
        score += 1

    if any(token in notes for token in ["under construction", "business.site", "no website"]):
        score += 1

    if website:
        score -= 2

    if link:
        netloc = urlparse(link).netloc.lower().replace("www.", "")
        if any(netloc == d or netloc.endswith(f".{d}") for d in DIRECTORY_DOMAIN_HINTS):
            score -= 1

    if STARTUP_PRIORITY:
        score += startup_signal_score(row)

    return score


def startup_signal_score(row):
    score = 0
    fields = [
        row.get("name", ""),
        row.get("notes", ""),
        row.get("link", ""),
        row.get("website", ""),
    ]
    blob = " ".join("" if pd.isna(v) else str(v) for v in fields).lower()

    if STARTUP_EXCLUDE_TECH and STARTUP_TECH_EXCLUDE_KEYWORDS:
        if any(token in blob for token in STARTUP_TECH_EXCLUDE_KEYWORDS):
            return 0

    # Prefer age-based startup detection over industry/TLD heuristics.
    current_year = datetime.now().year
    year_match = re.search(r"\\b(?:founded|est\\.?|established|since)\\s*(?:in\\s*)?(19\\d{2}|20\\d{2})\\b", blob)
    age_match = False
    if year_match:
        founded_year = int(year_match.group(1))
        age_years = current_year - founded_year
        if 0 <= age_years <= max(0, STARTUP_MAX_AGE_YEARS):
            age_match = True
            score += 1

    young_phrase_match = bool(re.search(r"\\bnewly opened|recently opened|just launched|new business|new company\\b", blob))
    if young_phrase_match:
        score += 1

    # Optional custom hints only count when paired with a young-age signal.
    if STARTUP_HINT_KEYWORDS and any(token in blob for token in STARTUP_HINT_KEYWORDS):
        if age_match or young_phrase_match:
            score += 1

    if score <= 0:
        return 0
    return max(0, STARTUP_SCORE_BOOST)


def can_reach_send_threshold(row, threshold):
    # Best case after enrichment: valid business-domain email (+2)
    # (+1 for having an email, +1 for non-free domain)
    return pre_enrich_base_score(row) + 2 >= threshold

# ======================================================
# PER-LEAD WORKER  (called from thread pool)
# ======================================================
def _process_lead(row: dict, town: str, service: str):
    """
    Enriches a single lead.  Designed to run concurrently — all shared
    state is either read-only or protected by _METRICS_LOCK.

    Returns: (result_row, skip_entirely, skipped_site, found_email, skipped_score)
      result_row   – enriched dict, or None when skip_entirely=True
      skip_entirely – True → exclude this row from the output CSV
      skipped_site  – True → increment the skipped_site counter
      found_email   – True → increment the found_emails counter
      skipped_score – True → increment the skipped_score_floor counter
    """
    website_val = row.get("website", "")
    existing_website = (
        "" if (website_val is None or (isinstance(website_val, float) and pd.isna(website_val)))
        else str(website_val).strip()
    )
    name = str(row.get("name", "") or "").strip()

    if existing_website:
        print(f"[SKIP-API] Existing website present for {name or '(unknown)'}: {existing_website}")
        return None, True, True, False, False

    if PRE_ENRICH_SCORE_FILTER and not can_reach_send_threshold(row, LEAD_SCORE_THRESHOLD):
        out = dict(row)
        out["emails"] = ""
        out["website"] = ""
        if DEBUG:
            print(f"[SCORE-FILTER] Skipping enrichment calls for {name or '(unknown)'}")
        return out, False, False, False, True

    query = (
        f"{name} {town} {service} contact OR email "
        f"-site:indeed.com -site:yelp.com -site:nextdoor.com -site:linkedin.com "
        f"-site:facebook.com -site:houzz.com -site:thumbtack.com -site:angi.com "
        f"-site:yellowpages.com -site:mapquest.com"
    )
    links = search_serper(query)
    emails_found = []
    confirmed_site = ""

    candidate_domains = []
    for link in links:
        domain = urlparse(link).netloc.lower()
        if not domain:
            continue
        domain = domain.replace("www.", "")

        if is_non_business_domain(domain):
            if DEBUG:
                print(f"[SKIP-DOMAIN] Non-business candidate domain: {domain}")
            continue

        if is_confirmed_business_website(domain, business_name=name):
            confirmed_site = f"http://{domain}"
            if DEBUG:
                print(f"[SKIP] Confirmed business website: {domain}")
            break

        if domain not in candidate_domains:
            candidate_domains.append(domain)

    if not confirmed_site and DEBUG and len(candidate_domains) > SCRAPE_MAX_DOMAINS > 0:
        print(
            f"[SCRAPE-CAP] Limiting domain checks to {SCRAPE_MAX_DOMAINS} "
            f"of {len(candidate_domains)} candidate domains"
        )

    for domain in ([] if confirmed_site else candidate_domains[:SCRAPE_MAX_DOMAINS]):
        emails = scrape_emails_from_website(domain)
        if not emails and HUNTER:
            emails = hunter_email_lookup(domain)
        viable_emails = filter_viable_emails(emails)
        if viable_emails:
            email_domain = viable_emails[0].split("@", 1)[1].lower()
            if is_confirmed_business_website(email_domain, business_name=name):
                confirmed_site = f"http://{email_domain}"
                if DEBUG:
                    print(f"[SKIP] Confirmed website via email domain: {email_domain}")
                break

            if (
                not is_non_business_domain(domain)
                and not is_non_business_domain(email_domain)
                and not is_placeholder_domain(domain)
                and not is_placeholder_domain(email_domain)
                and domains_look_equivalent(domain, email_domain)
                and business_name_matches_domain(name, email_domain)
            ):
                confirmed_site = f"http://{email_domain}"
                if DEBUG:
                    print(f"[SKIP] Domain-match website signal: {domain} ~= {email_domain}")
                break

            emails_found = viable_emails
            break

    if confirmed_site:
        if DEBUG:
            print(f"[SKIP2] {confirmed_site} already live.")
        return None, True, True, False, False

    out = dict(row)
    if emails_found:
        out["emails"] = ", ".join(emails_found)
        out["website"] = ""
        return out, False, False, True, False
    else:
        out["emails"] = ""
        out["website"] = ""
        return out, False, False, False, False


# ======================================================
# ENRICH MAIN
# ======================================================
def enrich(service, town, max_leads=None):
    try:
        emit_structured_event(
            "enrichment_start",
            enabled=STRUCTURED_LOGGING_ENABLED,
            service=service,
            city=town,
            max_leads=max_leads,
        )
        safe_town = sanitize_for_filename(town)
        safe_service = sanitize_for_filename(service)

        in_fname = f"leads_{safe_town}_{safe_service}_NO_WEBSITE_{DATESTAMP}.csv"
        in_path = os.path.join(DATA_DIR, in_fname)
        out_path = os.path.join(DATA_DIR, in_fname)

        if not os.path.isfile(in_path):
            legacy_fname = f"leads_{town}_{service}_NO_WEBSITE_{DATESTAMP}.csv"
            legacy_path = os.path.join(DATA_DIR, legacy_fname)
            if os.path.isfile(legacy_path):
                in_fname = legacy_fname
                in_path = legacy_path

        if not os.path.isfile(in_path):
            print(f"[WARN] No discovery data found → {in_path}")
            emit_structured_event(
                "enrichment_missing_input",
                enabled=STRUCTURED_LOGGING_ENABLED,
                service=service,
                city=town,
                input_file=in_path,
            )
            return None

        # Rerun protection: skip if this run's output already exists with non-empty emails.
        if os.path.isfile(out_path):
            try:
                existing_df = pd.read_csv(out_path)
                has_enriched_emails = (
                    "emails" in existing_df.columns
                    and existing_df["emails"].fillna("").astype(str).str.strip().ne("").any()
                )
                if has_enriched_emails:
                    print(f"[SKIP] Enrichment already done for {out_path}")
                    emit_structured_event(
                        "enrichment_skipped_existing_output",
                        enabled=STRUCTURED_LOGGING_ENABLED,
                        service=service,
                        city=town,
                        output_file=out_path,
                    )
                    return out_path
            except Exception:
                # Fall through and run enrichment if we cannot validate existing output.
                pass

        df = pd.read_csv(in_path)
        if df.empty:
            print(f"[WARN] Empty CSV → {town}|{service}")
            return None

        if max_leads is not None:
            max_leads = max(int(max_leads), 0)
            if max_leads == 0:
                print("[INFO] max_leads=0; skipping enrichment work.")
                return in_path
            df = df.head(max_leads)

        enriched, skipped_site, found_emails, skipped_score_floor = [], 0, 0, 0
        print(f"[INFO] Enriching {len(df)} leads for {town.title()} – {service.title()} "
              f"(workers={ENRICH_WORKERS}) …")

        rows = [r.to_dict() for _, r in df.iterrows()]
        with ThreadPoolExecutor(max_workers=ENRICH_WORKERS) as pool:
            futures = [pool.submit(_process_lead, row, town, service) for row in rows]
            for future in as_completed(futures):
                result_row, skip_entirely, s_site, f_email, s_score = future.result()
                if s_site:
                    skipped_site += 1
                if f_email:
                    found_emails += 1
                if s_score:
                    skipped_score_floor += 1
                if not skip_entirely and result_row is not None:
                    enriched.append(result_row)

        if not enriched:
            print(f"[WARN] No usable leads for {town}|{service}")
            emit_structured_event(
                "enrichment_no_usable_leads",
                enabled=STRUCTURED_LOGGING_ENABLED,
                service=service,
                city=town,
            )
            return None

        pd.DataFrame(enriched).drop_duplicates(subset=["name"]).to_csv(out_path, index=False)

        print(f"[✅] Saved {len(enriched)} leads → {out_path}")
        print(f"   ↳ Skipped (business had site): {skipped_site}")
        print(f"   ↳ Skipped (pre‑enrich score floor): {skipped_score_floor}")
        print(f"   ↳ With verified emails: {found_emails}")
        emit_structured_event(
            "enrichment_complete",
            enabled=STRUCTURED_LOGGING_ENABLED,
            service=service,
            city=town,
            total_rows=int(len(enriched)),
            skipped_site=int(skipped_site),
            skipped_score_floor=int(skipped_score_floor),
            verified_email_rows=int(found_emails),
            output_file=out_path,
        )
        return out_path

    except Exception as e:
        print(f"[❌] Fatal error during enrichment: {e}")
        emit_structured_event(
            "enrichment_error",
            enabled=STRUCTURED_LOGGING_ENABLED,
            service=service,
            city=town,
            error=str(e),
        )
        traceback.print_exc()
        return None

# ======================================================
# ENTRYPOINT
# ======================================================
if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python3 enrich_leads.py <service> <city>")
    else:
        max_leads_arg = int(sys.argv[3]) if len(sys.argv) > 3 else None
        enrich(sys.argv[1], sys.argv[2], max_leads=max_leads_arg)