#!/usr/bin/env python3
"""
find_no_website_emails.py
------------------------------------------------------
Enhanced enrichment logic — skips any lead with a live website.

Purpose:
• Enrich Directory/No‑Site leads generated by Discover Mode.
• Verify actual website existence for each discovered lead.
• Fetch up to one confirmed contact email if no valid site.

------------------------------------------------------
"""

import os, re, time, json, hashlib, requests, pandas as pd, traceback
from urllib.parse import urlparse
from dotenv import load_dotenv
from datetime import datetime, timedelta

# ======================================================
# ENV SETUP
# ======================================================
load_dotenv()
SERPER = os.getenv("SERPER_API_KEY")
HUNTER = os.getenv("HUNTER_API_KEY")
DEBUG = os.getenv("DEBUG", "false").lower() == "true"
LEAD_SCORE_THRESHOLD = int(os.getenv("LEAD_SCORE_THRESHOLD", "2"))
PRE_ENRICH_SCORE_FILTER = os.getenv("PRE_ENRICH_SCORE_FILTER", "true").strip().lower() in {"1", "true", "yes", "on"}
STARTUP_PRIORITY = os.getenv("STARTUP_PRIORITY", "false").strip().lower() in {"1", "true", "yes", "on"}
STARTUP_SCORE_BOOST = int(os.getenv("STARTUP_SCORE_BOOST", "2"))
STARTUP_MAX_AGE_YEARS = int(os.getenv("STARTUP_MAX_AGE_YEARS", "5"))
STARTUP_EXCLUDE_TECH = os.getenv("STARTUP_EXCLUDE_TECH", "true").strip().lower() in {"1", "true", "yes", "on"}
STARTUP_HINT_KEYWORDS = tuple(
    token.strip().lower()
    for token in os.getenv(
        "STARTUP_HINT_KEYWORDS",
        "founded,established,since,newly opened,recently opened,just launched,new business,new company",
    ).split(",")
    if token.strip()
)
STARTUP_TECH_EXCLUDE_KEYWORDS = tuple(
    token.strip().lower()
    for token in os.getenv(
        "STARTUP_TECH_EXCLUDE_KEYWORDS",
        "saas,software,app,platform,ai,ml,machine learning,cloud,devops,fintech,edtech,martech",
    ).split(",")
    if token.strip()
)

BASE_DIR = "/Users/alexcahn/Scripts/Daily_Leads"
DATA_DIR = os.path.join(BASE_DIR, "data")
CACHE_DIR = os.path.join(DATA_DIR, "cache")
DATESTAMP = datetime.now().strftime("%Y-%m-%d")
CACHE_TTL_DAYS = int(os.getenv("CACHE_TTL_DAYS", "7"))
CACHE_MAX_MB = int(os.getenv("CACHE_MAX_MB", "256"))
RUN_METRICS_FILE = os.getenv("PIPELINE_RUN_METRICS_FILE", "")

RUN_METRICS_TEMPLATE = {
    "google_places": 0,
    "serper": 0,
    "hunter": 0,
    "google_places_calls": 0,
    "google_places_success": 0,
    "google_places_error": 0,
    "google_places_cache_hit": 0,
    "google_places_latency_ms_sum": 0,
    "google_places_latency_ms_count": 0,
    "serper_calls": 0,
    "serper_success": 0,
    "serper_error": 0,
    "serper_cache_hit": 0,
    "serper_latency_ms_sum": 0,
    "serper_latency_ms_count": 0,
    "hunter_calls": 0,
    "hunter_success": 0,
    "hunter_error": 0,
    "hunter_cache_hit": 0,
    "hunter_latency_ms_sum": 0,
    "hunter_latency_ms_count": 0,
}

os.makedirs(CACHE_DIR, exist_ok=True)

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; ZBA‑LeadBot/1.1)"}
FREE_EMAIL_DOMAINS = {
    "gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "icloud.com", "aol.com"
}

DIRECTORY_DOMAIN_HINTS = {
    "yelp.com",
    "indeed.com",
    "nextdoor.com",
    "houzz.com",
    "zocdoc.com",
    "pinterest.com",
    "medium.com",
    "facebook.com",
    "linkedin.com",
    "thumbtack.com",
    "angi.com",
    "angieslist.com",
    "yellowpages.com",
    "mapquest.com",
    "tripadvisor.com",
}

NON_BUSINESS_EMAIL_DOMAIN_HINTS = {
    "yelp.com",
    "indeed.com",
    "nextdoor.com",
    "linkedin.com",
    "facebook.com",
    "houzz.com",
    "thumbtack.com",
    "angi.com",
    "angieslist.com",
    "yellowpages.com",
    "mapquest.com",
    "zoominfo.com",
    "manta.com",
    "care.com",
}


def sanitize_for_filename(value: str) -> str:
    return re.sub(r'[^A-Za-z0-9_]+', '_', str(value).strip()).strip('_')


def _cache_path(prefix: str, key: str) -> str:
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
    return os.path.join(CACHE_DIR, f"{prefix}_{digest}.json")


def cache_get(prefix: str, key: str):
    path = _cache_path(prefix, key)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            payload = json.load(f)
        created = datetime.fromisoformat(payload.get("created_at", "1970-01-01T00:00:00"))
        if datetime.now() - created > timedelta(days=CACHE_TTL_DAYS):
            return None
        provider = metric_provider_for_cache_prefix(prefix)
        if provider:
            increment_metric(f"{provider}_cache_hit")
        return payload.get("value")
    except Exception:
        return None


def cache_set(prefix: str, key: str, value):
    path = _cache_path(prefix, key)
    payload = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "value": value,
    }
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f)
    except Exception:
        pass


def load_run_metrics():
    data = dict(RUN_METRICS_TEMPLATE)
    if not RUN_METRICS_FILE or not os.path.isfile(RUN_METRICS_FILE):
        return data
    try:
        with open(RUN_METRICS_FILE, "r", encoding="utf-8") as f:
            loaded = json.load(f)
        for key in data:
            data[key] = int(loaded.get(key, 0) or 0)
    except Exception:
        pass
    return data


def save_run_metrics(data):
    if not RUN_METRICS_FILE:
        return
    try:
        with open(RUN_METRICS_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f)
    except Exception:
        pass


def increment_metric(metric_key: str, amount: int = 1):
    if not RUN_METRICS_FILE:
        return
    try:
        data = load_run_metrics()
        if metric_key in data:
            data[metric_key] += int(amount)
            save_run_metrics(data)
    except Exception:
        pass


def increment_api_counter(provider: str):
    """Backward-compatible shim for legacy tests/callers."""
    increment_metric(provider)


def metric_provider_for_cache_prefix(prefix: str) -> str:
    if (prefix or "").startswith("google_place") or prefix == "google_places":
        return "google_places"
    if prefix == "serper":
        return "serper"
    if prefix == "hunter":
        return "hunter"
    return ""


def record_api_outcome(provider: str, success: bool, latency_ms: int):
    if provider not in {"google_places", "serper", "hunter"}:
        return
    increment_metric(provider)
    increment_metric(f"{provider}_calls")
    increment_metric(f"{provider}_success" if success else f"{provider}_error")
    increment_metric(f"{provider}_latency_ms_sum", max(0, int(latency_ms)))
    increment_metric(f"{provider}_latency_ms_count")


def run_tracked_api_call(provider: str, request_func):
    started = time.perf_counter()
    try:
        result = request_func()
        latency_ms = int((time.perf_counter() - started) * 1000)
        record_api_outcome(provider, success=True, latency_ms=latency_ms)
        return result
    except Exception:
        latency_ms = int((time.perf_counter() - started) * 1000)
        record_api_outcome(provider, success=False, latency_ms=latency_ms)
        raise


def prune_expired_cache():
    cutoff = datetime.now() - timedelta(days=CACHE_TTL_DAYS)
    removed = 0
    if not os.path.isdir(CACHE_DIR):
        return removed
    for name in os.listdir(CACHE_DIR):
        if not name.endswith(".json"):
            continue
        path = os.path.join(CACHE_DIR, name)
        try:
            with open(path, "r", encoding="utf-8") as f:
                payload = json.load(f)
            created = datetime.fromisoformat(payload.get("created_at", "1970-01-01T00:00:00"))
            if created < cutoff:
                os.remove(path)
                removed += 1
        except Exception:
            pass
    if removed:
        print(f"[CACHE] Pruned {removed} expired cache file(s).")
    return removed


def prune_cache_size_limit():
    if CACHE_MAX_MB <= 0 or not os.path.isdir(CACHE_DIR):
        return 0

    limit_bytes = CACHE_MAX_MB * 1024 * 1024
    files = []
    total_size = 0

    for name in os.listdir(CACHE_DIR):
        if not name.endswith(".json"):
            continue
        path = os.path.join(CACHE_DIR, name)
        try:
            stat = os.stat(path)
            files.append((path, stat.st_mtime, stat.st_size))
            total_size += stat.st_size
        except Exception:
            continue

    if total_size <= limit_bytes:
        return 0

    files.sort(key=lambda item: item[1])
    removed = 0
    for path, _, file_size in files:
        if total_size <= limit_bytes:
            break
        try:
            os.remove(path)
            removed += 1
            total_size -= file_size
        except Exception:
            continue

    if removed:
        print(f"[CACHE] Pruned {removed} cache file(s) to enforce CACHE_MAX_MB={CACHE_MAX_MB}.")
    return removed


prune_expired_cache()
prune_cache_size_limit()

# ======================================================
# RETRY WRAPPER
# ======================================================
def retry_request(func, *args, **kwargs):
    for attempt in range(2):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            if "429" in str(e):
                wait = 10 if attempt == 0 else 30
                print(f"[RATE] 429 Too Many Requests → waiting {wait}s…")
                time.sleep(wait)
            else:
                wait = 3 * (attempt + 1)
                print(f"[RETRY] {e} (wait {wait}s)")
                time.sleep(wait)
    print("[❌] All retries failed.")
    return None

# ======================================================
# BASIC SEARCH (SERPER)
# ======================================================
def search_serper(query):
    if not SERPER:
        return []
    cached = cache_get("serper", query)
    if cached is not None:
        return cached
    def _call():
        payload = {"q": query, "num": 5}
        headers = {"X-API-KEY": SERPER, "Content-Type": "application/json"}

        def _request():
            r = requests.post("https://google.serper.dev/search",
                              headers=headers, json=payload, timeout=25)
            r.raise_for_status()
            data = r.json().get("organic", [])
            return [x.get("link") for x in data if x.get("link")]

        return run_tracked_api_call("serper", _request)
    result = retry_request(_call) or []
    cache_set("serper", query, result)
    return result

# ======================================================
# WEBSITE CHECK — small HEAD request
# ======================================================
def has_live_website(domain):
    """Quickly check if the domain responds with status 200/OK + visible homepage text."""
    if not domain:
        return False

    clean_domain = (domain or "").strip().lower().replace("www.", "")
    if not clean_domain:
        return False

    for candidate in (f"https://{clean_domain}", f"http://{clean_domain}"):
        try:
            resp = requests.get(candidate, headers=HEADERS, timeout=6, allow_redirects=True)
            if 200 <= resp.status_code < 400:
                content_type = (resp.headers.get("Content-Type", "") or "").lower()
                body = (resp.text or "")[:3000]
                if "html" in content_type or re.search(r"<html|<!doctype", body, re.I):
                    return True
        except Exception:
            continue
    return False


def is_confirmed_business_website(url_or_domain: str, business_name: str = "") -> bool:
    value = (url_or_domain or "").strip().lower()
    if not value:
        return False

    parsed = urlparse(value if "://" in value else f"http://{value}")
    domain = (parsed.netloc or parsed.path or "").lower().replace("www.", "").strip()
    if not domain or "." not in domain:
        return False

    if any(domain == d or domain.endswith(f".{d}") for d in DIRECTORY_DOMAIN_HINTS):
        return False

    if domain.endswith(".gov") or domain.endswith(".edu"):
        return False

    return has_live_website(domain)


def is_non_business_domain(domain: str) -> bool:
    clean_domain = (domain or "").strip().lower().replace("www.", "")
    if not clean_domain:
        return True
    return any(
        clean_domain == hint or clean_domain.endswith(f".{hint}")
        for hint in DIRECTORY_DOMAIN_HINTS
    )


def is_viable_email_address(email_addr: str) -> bool:
    value = (email_addr or "").strip().lower()
    if not value or "@" not in value:
        return False
    domain = value.split("@", 1)[1]
    if not domain or "." not in domain:
        return False
    if any(domain == hint or domain.endswith(f".{hint}") for hint in NON_BUSINESS_EMAIL_DOMAIN_HINTS):
        return False
    return True


def filter_viable_emails(emails):
    viable = []
    seen = set()
    for email_addr in emails or []:
        normalized = (email_addr or "").strip().lower()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        if is_viable_email_address(normalized):
            viable.append(normalized)
    return viable

# ======================================================
# HUNTER LOOKUP
# ======================================================
def hunter_email_lookup(domain):
    if not (HUNTER and domain):
        return []
    cached = cache_get("hunter", domain)
    if cached is not None:
        return cached
    def _call():

        def _request():
            r = requests.get("https://api.hunter.io/v2/domain-search",
                             params={"domain": domain, "api_key": HUNTER},
                             timeout=15)
            r.raise_for_status()
            emails = r.json().get("data", {}).get("emails", [])
            return [e.get("value") for e in emails if e.get("value")]

        return run_tracked_api_call("hunter", _request)
    result = retry_request(_call) or []
    cache_set("hunter", domain, result)
    return result


def pre_enrich_base_score(row):
    score = 0
    business_val = row.get("name", "")
    notes_val = row.get("notes", "")
    website_val = row.get("website", "")
    link_val = row.get("link", "")

    business = "" if pd.isna(business_val) else str(business_val).strip()
    notes = "" if pd.isna(notes_val) else str(notes_val).lower()
    website = "" if pd.isna(website_val) else str(website_val).strip()
    link = "" if pd.isna(link_val) else str(link_val).strip().lower()

    if len(business.split()) >= 2:
        score += 1

    if any(token in notes for token in ["under construction", "business.site", "no website"]):
        score += 1

    if website:
        score -= 2

    if link:
        netloc = urlparse(link).netloc.lower().replace("www.", "")
        if any(netloc == d or netloc.endswith(f".{d}") for d in DIRECTORY_DOMAIN_HINTS):
            score -= 1

    if STARTUP_PRIORITY:
        score += startup_signal_score(row)

    return score


def startup_signal_score(row):
    score = 0
    fields = [
        row.get("name", ""),
        row.get("notes", ""),
        row.get("link", ""),
        row.get("website", ""),
    ]
    blob = " ".join("" if pd.isna(v) else str(v) for v in fields).lower()

    if STARTUP_EXCLUDE_TECH and STARTUP_TECH_EXCLUDE_KEYWORDS:
        if any(token in blob for token in STARTUP_TECH_EXCLUDE_KEYWORDS):
            return 0

    # Prefer age-based startup detection over industry/TLD heuristics.
    current_year = datetime.now().year
    year_match = re.search(r"\\b(?:founded|est\\.?|established|since)\\s*(?:in\\s*)?(19\\d{2}|20\\d{2})\\b", blob)
    age_match = False
    if year_match:
        founded_year = int(year_match.group(1))
        age_years = current_year - founded_year
        if 0 <= age_years <= max(0, STARTUP_MAX_AGE_YEARS):
            age_match = True
            score += 1

    young_phrase_match = bool(re.search(r"\\bnewly opened|recently opened|just launched|new business|new company\\b", blob))
    if young_phrase_match:
        score += 1

    # Optional custom hints only count when paired with a young-age signal.
    if STARTUP_HINT_KEYWORDS and any(token in blob for token in STARTUP_HINT_KEYWORDS):
        if age_match or young_phrase_match:
            score += 1

    if score <= 0:
        return 0
    return max(0, STARTUP_SCORE_BOOST)


def can_reach_send_threshold(row, threshold):
    # Best case after enrichment: valid business-domain email (+2)
    # (+1 for having an email, +1 for non-free domain)
    return pre_enrich_base_score(row) + 2 >= threshold

# ======================================================
# ENRICH MAIN
# ======================================================
def enrich(service, town, max_leads=None):
    try:
        safe_town = sanitize_for_filename(town)
        safe_service = sanitize_for_filename(service)

        in_fname = f"leads_{safe_town}_{safe_service}_NO_WEBSITE_{DATESTAMP}.csv"
        in_path = os.path.join(DATA_DIR, in_fname)

        if not os.path.isfile(in_path):
            legacy_fname = f"leads_{town}_{service}_NO_WEBSITE_{DATESTAMP}.csv"
            legacy_path = os.path.join(DATA_DIR, legacy_fname)
            if os.path.isfile(legacy_path):
                in_fname = legacy_fname
                in_path = legacy_path

        if not os.path.isfile(in_path):
            print(f"[WARN] No discovery data found → {in_path}")
            return None

        df = pd.read_csv(in_path)
        if df.empty:
            print(f"[WARN] Empty CSV → {town}|{service}")
            return None

        if max_leads is not None:
            max_leads = max(int(max_leads), 0)
            if max_leads == 0:
                print("[INFO] max_leads=0; skipping enrichment work.")
                return in_path
            df = df.head(max_leads)

        enriched, skipped_site, found_emails, skipped_score_floor = [], 0, 0, 0
        print(f"[INFO] Enriching {len(df)} leads for {town.title()} – {service.title()} …")

        for _, row in df.iterrows():
            website_val = row.get("website", "")
            existing_website = "" if pd.isna(website_val) else str(website_val).strip()
            name = str(row.get("name", "")).strip()

            if existing_website:
                skipped_site += 1
                safe_name = name or "(unknown)"
                print(f"[SKIP-API] Existing website present for {safe_name}: {existing_website}")
                continue

            if PRE_ENRICH_SCORE_FILTER and not can_reach_send_threshold(row, LEAD_SCORE_THRESHOLD):
                skipped_score_floor += 1
                row["emails"] = ""
                row["website"] = ""
                enriched.append(row)
                if DEBUG:
                    name = str(row.get("name", "")).strip() or "(unknown)"
                    print(f"[SCORE-FILTER] Skipping enrichment calls for {name}")
                continue

            query = (
                f"{name} {town} {service} contact OR email "
                f"-site:indeed.com -site:yelp.com -site:nextdoor.com -site:linkedin.com "
                f"-site:facebook.com -site:houzz.com -site:thumbtack.com -site:angi.com "
                f"-site:yellowpages.com -site:mapquest.com"
            )
            links = search_serper(query)
            emails_found = []
            confirmed_site = ""

            for link in links:
                domain = urlparse(link).netloc.lower()
                if not domain:
                    continue
                domain = domain.replace("www.", "")

                if is_non_business_domain(domain):
                    if DEBUG:
                        print(f"[SKIP-DOMAIN] Non-business candidate domain: {domain}")
                    continue

                if is_confirmed_business_website(domain, business_name=name):
                    confirmed_site = f"http://{domain}"
                    if DEBUG:
                        print(f"[SKIP] Confirmed business website: {domain}")
                    break

                emails = hunter_email_lookup(domain)
                viable_emails = filter_viable_emails(emails)
                if viable_emails:
                    # Guardrail: if the email domain itself has a live business site,
                    # this is not a true no-website lead.
                    email_domain = viable_emails[0].split("@", 1)[1].lower()
                    if is_confirmed_business_website(email_domain, business_name=name):
                        confirmed_site = f"http://{email_domain}"
                        if DEBUG:
                            print(f"[SKIP] Confirmed website via email domain: {email_domain}")
                        break

                    emails_found = viable_emails
                    break

            if confirmed_site:
                skipped_site += 1
                if DEBUG:
                    print(f"[SKIP2] {confirmed_site} already live.")
                continue

            if emails_found:
                found_emails += 1
                row["emails"] = ", ".join(emails_found)
                row["website"] = ""
                enriched.append(row)
            else:
                # keep if truly no site/email found (potential cold)
                row["emails"] = ""
                row["website"] = ""
                enriched.append(row)

            time.sleep(1)

        if not enriched:
            print(f"[WARN] No usable leads for {town}|{service}")
            return None

        out_path = os.path.join(DATA_DIR, in_fname)
        pd.DataFrame(enriched).drop_duplicates(subset=["name"]).to_csv(out_path, index=False)

        print(f"[✅] Saved {len(enriched)} leads → {out_path}")
        print(f"   ↳ Skipped (business had site): {skipped_site}")
        print(f"   ↳ Skipped (pre‑enrich score floor): {skipped_score_floor}")
        print(f"   ↳ With verified emails: {found_emails}")
        return out_path

    except Exception as e:
        print(f"[❌] Fatal error during enrichment: {e}")
        traceback.print_exc()
        return None

# ======================================================
# ENTRYPOINT
# ======================================================
if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python3 find_no_website_emails.py <service> <city>")
    else:
        max_leads_arg = int(sys.argv[3]) if len(sys.argv) > 3 else None
        enrich(sys.argv[1], sys.argv[2], max_leads=max_leads_arg)