#!/usr/bin/env python3
"""
find_no_website_emails.py
------------------------------------------------------
Enhanced enrichment logic — skips any lead with a live website.

Purpose:
• Enrich Directory/No‑Site leads generated by Discover Mode.
• Verify actual website existence for each discovered lead.
• Fetch up to one confirmed contact email if no valid site.

------------------------------------------------------
"""

import os, re, time, json, hashlib, requests, pandas as pd, traceback
from urllib.parse import urlparse
from dotenv import load_dotenv
from datetime import datetime, timedelta

# ======================================================
# ENV SETUP
# ======================================================
load_dotenv()
SERPER = os.getenv("SERPER_API_KEY")
HUNTER = os.getenv("HUNTER_API_KEY")
DEBUG = os.getenv("DEBUG", "false").lower() == "true"

BASE_DIR = "/Users/alexcahn/Scripts/Daily_Leads"
DATA_DIR = os.path.join(BASE_DIR, "data")
CACHE_DIR = os.path.join(DATA_DIR, "cache")
DATESTAMP = datetime.now().strftime("%Y-%m-%d")
CACHE_TTL_DAYS = int(os.getenv("CACHE_TTL_DAYS", "7"))

os.makedirs(CACHE_DIR, exist_ok=True)

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; ZBA‑LeadBot/1.1)"}


def sanitize_for_filename(value: str) -> str:
    return re.sub(r'[^A-Za-z0-9_]+', '_', str(value).strip()).strip('_')


def _cache_path(prefix: str, key: str) -> str:
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
    return os.path.join(CACHE_DIR, f"{prefix}_{digest}.json")


def cache_get(prefix: str, key: str):
    path = _cache_path(prefix, key)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            payload = json.load(f)
        created = datetime.fromisoformat(payload.get("created_at", "1970-01-01T00:00:00"))
        if datetime.now() - created > timedelta(days=CACHE_TTL_DAYS):
            return None
        return payload.get("value")
    except Exception:
        return None


def cache_set(prefix: str, key: str, value):
    path = _cache_path(prefix, key)
    payload = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "value": value,
    }
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f)
    except Exception:
        pass

# ======================================================
# RETRY WRAPPER
# ======================================================
def retry_request(func, *args, **kwargs):
    for attempt in range(2):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            if "429" in str(e):
                wait = 10 if attempt == 0 else 30
                print(f"[RATE] 429 Too Many Requests → waiting {wait}s…")
                time.sleep(wait)
            else:
                wait = 3 * (attempt + 1)
                print(f"[RETRY] {e} (wait {wait}s)")
                time.sleep(wait)
    print("[❌] All retries failed.")
    return None

# ======================================================
# BASIC SEARCH (SERPER)
# ======================================================
def search_serper(query):
    if not SERPER:
        return []
    cached = cache_get("serper", query)
    if cached is not None:
        return cached
    def _call():
        payload = {"q": query, "num": 5}
        headers = {"X-API-KEY": SERPER, "Content-Type": "application/json"}
        r = requests.post("https://google.serper.dev/search",
                          headers=headers, json=payload, timeout=25)
        r.raise_for_status()
        data = r.json().get("organic", [])
        return [x.get("link") for x in data if x.get("link")]
    result = retry_request(_call) or []
    cache_set("serper", query, result)
    return result

# ======================================================
# WEBSITE CHECK — small HEAD request
# ======================================================
def has_live_website(domain):
    """Quickly check if the domain responds with status 200/OK + visible homepage text."""
    try:
        if not domain:
            return False
        resp = requests.get(f"http://{domain}", headers=HEADERS, timeout=5)
        if resp.status_code == 200 and re.search(r"<html|<!doctype", resp.text[:3000], re.I):
            return True
    except Exception:
        pass
    return False

# ======================================================
# HUNTER LOOKUP
# ======================================================
def hunter_email_lookup(domain):
    if not (HUNTER and domain):
        return []
    cached = cache_get("hunter", domain)
    if cached is not None:
        return cached
    def _call():
        r = requests.get("https://api.hunter.io/v2/domain-search",
                         params={"domain": domain, "api_key": HUNTER},
                         timeout=15)
        r.raise_for_status()
        emails = r.json().get("data", {}).get("emails", [])
        return [e.get("value") for e in emails if e.get("value")]
    result = retry_request(_call) or []
    cache_set("hunter", domain, result)
    return result

# ======================================================
# ENRICH MAIN
# ======================================================
def enrich(service, town, max_leads=None):
    try:
        safe_town = sanitize_for_filename(town)
        safe_service = sanitize_for_filename(service)

        in_fname = f"leads_{safe_town}_{safe_service}_NO_WEBSITE_{DATESTAMP}.csv"
        in_path = os.path.join(DATA_DIR, in_fname)

        if not os.path.isfile(in_path):
            legacy_fname = f"leads_{town}_{service}_NO_WEBSITE_{DATESTAMP}.csv"
            legacy_path = os.path.join(DATA_DIR, legacy_fname)
            if os.path.isfile(legacy_path):
                in_fname = legacy_fname
                in_path = legacy_path

        if not os.path.isfile(in_path):
            print(f"[WARN] No discovery data found → {in_path}")
            return None

        df = pd.read_csv(in_path)
        if df.empty:
            print(f"[WARN] Empty CSV → {town}|{service}")
            return None

        if max_leads is not None:
            max_leads = max(int(max_leads), 0)
            if max_leads == 0:
                print("[INFO] max_leads=0; skipping enrichment work.")
                return in_path
            df = df.head(max_leads)

        enriched, skipped_site, found_emails = [], 0, 0
        print(f"[INFO] Enriching {len(df)} leads for {town.title()} – {service.title()} …")

        for _, row in df.iterrows():
            name = str(row.get("name", "")).strip()
            query = f"{name} {town} {service} contact OR email"
            links = search_serper(query)
            emails_found = []
            site_found = None

            for link in links:
                domain = urlparse(link).netloc.lower()
                if not domain:
                    continue

                # Immediately skip if it looks like a personal site
                if has_live_website(domain):
                    skipped_site += 1
                    if DEBUG: print(f"[SKIP] Live site: {domain}")
                    site_found = f"http://{domain}"
                    break

                emails = hunter_email_lookup(domain)
                if emails:
                    emails_found = emails
                    site_found = f"http://{domain}"
                    break

            if site_found and has_live_website(urlparse(site_found).netloc):
                # double‑check before logging email
                skipped_site += 1
                if DEBUG:
                    print(f"[SKIP2] {site_found} already live.")
                continue

            if emails_found:
                found_emails += 1
                row["emails"] = ", ".join(emails_found)
                row["website"] = site_found or ""
                enriched.append(row)
            else:
                # keep if truly no site/email found (potential cold)
                row["emails"] = ""
                row["website"] = ""
                enriched.append(row)

            time.sleep(1)

        if not enriched:
            print(f"[WARN] No usable leads for {town}|{service}")
            return None

        out_path = os.path.join(DATA_DIR, in_fname)
        pd.DataFrame(enriched).drop_duplicates(subset=["name"]).to_csv(out_path, index=False)

        print(f"[✅] Saved {len(enriched)} leads → {out_path}")
        print(f"   ↳ Skipped (business had site): {skipped_site}")
        print(f"   ↳ With verified emails: {found_emails}")
        return out_path

    except Exception as e:
        print(f"[❌] Fatal error during enrichment: {e}")
        traceback.print_exc()
        return None

# ======================================================
# ENTRYPOINT
# ======================================================
if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python3 find_no_website_emails.py <service> <city>")
    else:
        max_leads_arg = int(sys.argv[3]) if len(sys.argv) > 3 else None
        enrich(sys.argv[1], sys.argv[2], max_leads=max_leads_arg)